apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: zhyfv58gq-go 
  janus-idp.io/tekton: zhyfv58gq-go
  backstage.io/kubernetes-id: zhyfv58gq-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: zhyfv58gq-go
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml